[UI]
# Name of the app and chatbot.
name = "Chatbot"

# Description of the app and chatbot. This is used for HTML tags.
# description = ""

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

[UI.theme]
  #layout = "wide"
  #font_family = "Inter, sans-serif"
  # Override default MUI light theme. (Check theme.ts)
  [UI.theme.light]
      #background = "#FAFAFA"
      #paper = "#FFFFFF"

      [UI.theme.light.primary]
          #main = "#F80061"
          #dark = "#980039"
          #light = "#FFE7EB"

  # Override default MUI dark theme. (Check theme.ts)
  [UI.theme.dark]
      #background = "#FAFAFA"
      #paper = "#FFFFFF"

      [UI.theme.dark.primary]
          #main = "#F80061"
          #dark = "#980039"
          #light = "#FFE7EB"
